### ISSUE TITLE
Possible security issue?

### ISSUE THREAD

**Issue by idpolik** [makitsune/blahaj-finder#5]
old/generate.mjs, line 21, contains your Ikea API key:
```
"X-Client-Id": "b6c117e5-ae61-4ef5-b4cc-e0b1e37f0631"
```
While I appreciate the gesture of providing me with a key to use for my own projects, I don't thing pushing it to GitHub is necessarily a very secure idea. I'm not too familiar with the Ikea API; I tried a key I got from a simple request to ikea.us, and I was unable to use it, therefore I believe yours has some sort of special privilege which you may not want public. Cheers

**Comment by makinori** [comment]
I don't have access to the Ikea API or even a login, I just took the header out of their site
